import { ResilientError } from '@owlmeans/error'
import { ModerationCategory } from '@owlmeans/viable-common'

/**
 * One refusal: the marker it travels as, and the sentence a parent agent reads instead of it.
 *
 * The marker is matched as a SUBSTRING of the error's own message, never by class. Every refusal
 * the platform raises is declared in a package this one does not depend on — the conversion family
 * in the platform's `viable-common`, the converter's own in `@owlmeans/viable-converter` — so an
 * `instanceof` here is impossible, and `ResilientError.ensure` rebuilds an unregistered class as a
 * bare error carrying the whole marshalled string. The same rule the browser follows for the same
 * reason: a refusal arrives thrown from a call AND stored as text on a job that failed, and only
 * the marker survives both.
 */
export interface RefusalPhrase {
  /** The marker as it appears inside the message, without the package prefix where that is safe. */
  marker: string
  /** The sentence, given whatever followed the marker (`''` where nothing did). */
  phrase: (detail: string) => string
}

/** What each moderation category refused, in the words the refusal is explained with. */
const MODERATION: Record<string, string> = {
  [ModerationCategory.CredentialHarvesting]:
    'collecting other people\'s passwords, one-time codes or card details',
  [ModerationCategory.BrandImpersonation]:
    'presenting itself as another company or as a real person',
  [ModerationCategory.PaymentCapture]:
    'taking payment details on behalf of a merchant the requester does not run',
  [ModerationCategory.AbuseTooling]:
    'abuse — unsolicited bulk messaging, credential stuffing or phishing kits',
}

/** ` (detail)`, or nothing at all: a phrase must read as a sentence when there is no detail. */
const aside = (detail: string): string => detail !== '' ? ` (${detail})` : ''

/**
 * Every refusal a connector can be handed, and the one sentence it is handed instead.
 *
 * Ordered by SPECIFICITY, because the first marker the message contains wins: every reason of a
 * family sits above the family's own marker, or the family would answer for all of them. A marker
 * that is a substring of a later one is a marker that shadows it, which `catalogue.spec.ts` pins
 * rather than leaves to review.
 *
 * The markers are literals here on purpose. They are wire text owned by packages this one does not
 * depend on, and copying the constant would need a dependency edge from a tooling package onto the
 * platform's own — so they are spelled once, in the order the platform spells them, and are
 * exactly the substrings the manager's own phrasing matches on. Anything unmatched falls back to
 * its marker, which is the one outcome that stays honest as the platform grows a refusal this
 * table has never heard of.
 */
export const REFUSALS: RefusalPhrase[] = [
  // ── A conversion refused by the platform ────────────────────────────────────────────────────
  {
    marker: 'conversion:unsupported:monorepo',
    phrase: paths => 'This repository points at code that is not inside it — a git submodule, or a'
      + ' workspace package that lives elsewhere. Converting needs everything in one repository.'
      + (paths !== '' ? `\nunlinked: ${paths}` : ''),
  },
  {
    marker: 'conversion:unsupported:bad-origin-url',
    phrase: url => 'That is not a repository address the platform can clone. Give the repository\'s'
      + ' own address, in the form https://github.com/owner/repository.'
      + (url !== '' ? `\ngiven: ${url}` : ''),
  },
  {
    marker: 'conversion:unsupported:not-linked',
    phrase: () => 'The platform has no way to read that repository: no GitHub connection is'
      + ' recorded for this project, or its access was revoked. The user connects it in the web'
      + ' application, and the conversion is started again afterwards.',
  },
  {
    marker: 'conversion:unsupported:no-origin',
    phrase: () => 'This project was generated by the platform rather than imported, so there is'
      + ' nothing to convert. develop_story is what changes a generated project.',
  },
  {
    marker: 'conversion:unsupported:not-convertible',
    phrase: () => 'The intake refused this origin: a conversion needs an application with source'
      + ' code it can read, not an empty repository, a documentation site or a bundle of binaries.'
      + ' check_convertible carries the reasons it gave.',
  },
  {
    marker: 'conversion:unsupported:',
    phrase: reason => `This origin cannot be converted${aside(reason)}, and no retry changes that.`
      + ' check_convertible carries the reasons.',
  },
  {
    marker: 'conversion:stage:',
    phrase: asked => `That decision is not available from where the conversion stands${aside(asked)}.`
      + ' Call conversion_status for the stage it is on and the decision it takes now.',
  },
  {
    marker: 'conversion:clone-failed:',
    phrase: () => 'The origin\'s sources could not be fetched. Check the repository still exists and'
      + ' that the project\'s GitHub connection still reaches it, then'
      + ' proceed_conversion { "decision": "retry" }.',
  },
  {
    marker: 'conversion:purge-in-place',
    phrase: () => 'Nothing to purge: the original sources are the project itself (an in-place'
      + ' repair). It was converted where it stood rather than rebuilt beside a filed-away copy,'
      + ' so there is no __viable_converted/ to delete and nothing has been removed.',
  },
  {
    marker: 'conversion:publish-origin',
    phrase: () => 'That would publish onto the repository this project was imported FROM, and its'
      + ' original sources are still on the volume — the push would write over the user\'s own'
      + ' code. purge_origin first, or publish to a different repository.',
  },
  {
    marker: 'conversion:relocate-declined',
    phrase: () => 'The conversion builds the new application around the existing code, which means'
      + ' moving that code one level down into __viable_converted/; nothing is deleted. The move'
      + ' was declined, so the conversion stopped here. Start it again and answer yes when it asks.',
  },

  // ── A conversion refused by the converter itself, usually reaching a parent on a failed job ──
  {
    marker: 'viable-converter:not-convertible:',
    phrase: reason => `The origin is not an application this platform can convert${aside(reason)}.`,
  },
  {
    marker: 'viable-converter:unsupported-stack:',
    phrase: stack => `The origin is built on a stack this converter carries no knowledge of${aside(stack)}.`
      + ' Nothing retries into a stack it cannot read.',
  },
  {
    marker: 'viable-converter:unlinked:',
    phrase: paths => 'The origin depends on code that is not inside it, so there is no one tree to'
      + ' convert.' + (paths !== '' ? `\nunlinked: ${paths}` : ''),
  },
  {
    marker: 'viable-converter:stage-order:',
    phrase: asked => `A conversion stage was asked for out of order${aside(asked)}.`
      + ' conversion_status says which one comes next.',
  },
  {
    marker: 'viable-converter:capability:',
    phrase: name => `The conversion needs something this deployment does not provide${aside(name)}.`
      + ' Nothing the parent agent does changes that; report it.',
  },
  {
    marker: 'viable-converter:too-large:',
    phrase: bytes => 'The origin is larger than a conversion reads'
      + (bytes !== '' ? ` (${bytes} bytes)` : '') + '.'
      + ' Convert a sub-project of it, or bring in a smaller tree.',
  },
  {
    marker: 'viable-converter:taxonomy-missing',
    phrase: () => 'This step needs what the ANALYSIS stage records, and the volume holds none of'
      + ' it. Run that stage first — proceed_conversion { "decision": "analyze" }.',
  },
  {
    marker: 'viable-converter:stack-missing',
    phrase: () => 'This step needs what the INTAKE stage records about the stack, and the volume'
      + ' holds none of it. The intake is what convert_project runs.',
  },
  {
    marker: 'viable-converter:origin-missing',
    phrase: () => 'The origin\'s sources are not on the volume: the stage that brings them in has'
      + ' not run. convert_project starts it.',
  },
  {
    marker: 'viable-converter:origin-purged',
    phrase: () => 'The original sources were deleted by purge_origin and this needs them. A purge'
      + ' cannot be undone.',
  },

  // ── What the platform refuses to build, whatever asked for it ────────────────────────────────
  {
    marker: 'content-refused:',
    phrase: category => 'The platform will not build this: it describes an application for '
      + (MODERATION[category] ?? 'something the platform does not host') + '.'
      + ' The refusal is about the SHAPE of the product, never its sector — say so to the user;'
      + ' re-sending the same description is refused the same way.',
  },
  {
    marker: 'reserved-name:',
    phrase: brand => (brand !== ''
      ? `"${brand}" is another company's name`
      : 'That name belongs to another company')
      + ', and a project name becomes part of its public web address. Choose a name of the user\'s'
      + ' own — the product may still work with that company.',
  },
  {
    marker: 'target-integrity:',
    phrase: files => 'The files in this project are not a Viable application, so nothing will be'
      + ' built or started from them.' + (files !== '' ? `\n${files}` : ''),
  },
  {
    marker: 'legacy-target:',
    phrase: () => 'This project was generated with an earlier application layout the platform no'
      + ' longer writes into. It keeps running, but no story or change can be applied to it.'
      + ' reinitialize_project rebuilds it with the current layout and keeps its stories.',
  },
  {
    marker: 'viable-project:missconfigured:',
    phrase: () => 'This project\'s analysis is missing from its sandbox, so there is nothing to'
      + ' build a story from. reinitialize_project restores it.',
  },

  // ── A balance, rather than a fault ───────────────────────────────────────────────────────────
  {
    marker: 'out-of-tokens:conversion-budget',
    phrase: () => 'The account balance will not cover this conversion stage. conversion_status'
      + ' carries the estimate; the balance is topped up in the web application.',
  },
  {
    marker: 'out-of-tokens:project-budget',
    phrase: () => 'The account balance is below the floor a new project needs. It is topped up in'
      + ' the web application.',
  },
  {
    marker: 'out-of-tokens:story-budget',
    phrase: () => 'The account balance will not cover developing a story. It is topped up in the'
      + ' web application.',
  },

  // ── The project is busy ──────────────────────────────────────────────────────────────────────
  {
    marker: 'viable-project:agent:occupied:',
    phrase: verb => `The platform is already working on this project${aside(verb)}.`
      + ' Poll the running job with wait_for and ask again once it settles.',
  },
  {
    // Spelled with its package prefix, unlike every marker above: `locked:` alone is a substring of
    // ordinary English and of `unlocked:`, and a false match would answer some other refusal with
    // this sentence.
    marker: 'viable-agent-common:locked:',
    phrase: task => `The platform holds this project's lock${aside(task)}.`
      + ' Poll the running job with wait_for and ask again once it settles.',
  },
  {
    marker: 'git-busy:',
    phrase: () => 'A git operation is already running on this project. Retry once it settles.',
  },

  // ── The connector, from the platform's side of it ────────────────────────────────────────────
  {
    marker: 'viable-connect:local-unsupported:',
    phrase: op => `That addresses infrastructure a local project does not have${aside(op)}:`
      + ' sandbox lifecycle, production, preview watching and remote git are cloud-target only.',
  },
  {
    marker: 'viable-connect:session-gone:',
    phrase: () => 'No connector is attached to this project any more, and this needs one. Call the'
      + ' tool again — a session is opened on demand — then resume_pipeline for the run that'
      + ' stopped.',
  },
  {
    marker: 'viable-connect:session-not-found:',
    phrase: () => 'That session has expired or belongs to another profile. Call the tool again; a'
      + ' session is opened on demand.',
  },
  {
    marker: 'viable-connect:op-timeout:',
    phrase: () => 'The connector did not answer within the operation\'s own deadline. Retry it.',
  },
  {
    marker: 'viable-connect:op-refused:',
    phrase: detail => `The connector ran the operation and refused it${aside(detail)}.`,
  },
  {
    marker: 'viable-connect:op-unknown:',
    phrase: () => 'That operation is unknown, already answered, or belongs to another session.',
  },

  // ── The call itself ──────────────────────────────────────────────────────────────────────────
  {
    marker: 'viable-api:agent:',
    phrase: verb => `The platform's agent could not complete this${aside(verb)}.`
      + ' project_status and conversion_status say where things stand; the call is retryable.',
  },
  {
    marker: 'api:client:auth:',
    phrase: () => 'The platform refused this access token. It is issued in the web application and'
      + ' can be revoked there — check VIABLE_API_TOKEN.',
  },
  {
    marker: 'api:client:crashed:',
    phrase: () => 'The platform errored on this call. Retry it, and read project_status for where'
      + ' the project actually stands before assuming nothing happened.',
  },
  {
    marker: 'api:client:forbidden',
    phrase: () => 'This token may not do that: the project belongs to another account, or the'
      + ' capability is not on this plan.',
  },
]

/** A stack frame, as every runtime prints one. */
const STACK_FRAME = /^\s+at\s/

/** Everything up to the first stack frame — a parent agent can act on none of what follows. */
const withoutStack = (text: string): string => {
  const lines = text.split('\n')
  const frame = lines.findIndex(line => STACK_FRAME.test(line))

  return (frame < 0 ? lines : lines.slice(0, frame)).join('\n').trim()
}

/**
 * Whether this error is what `ResilientError.ensure` leaves when NOTHING recognised the class.
 *
 * Its fall-through converter is `new resilientErrorClass(err.message, err.stack)` against a
 * constructor whose signature is `(type, message, stack)` — so `type` holds the original MESSAGE
 * and `message` holds the original STACK, with no marshalling separator anywhere to give the shape
 * away. Nothing about that path is exotic: `processResponse` in `@owlmeans/api` ensures ANY string
 * response body, and an edge 502/503 answers in plain text (`upstream connect error …`), so a
 * gateway failure was handed to the parent agent as a trace of the SDK's own frames.
 *
 * It is recognised by the head every runtime prints for a stack — `<Name>: <message>` followed by
 * the frames — and what survives is the message the runtime put there, which for the plain-text
 * body IS the refusal. The check is deliberately positional rather than a regex over `<Name>`: the
 * type can itself be a whole marshalled string carrying newlines, and only the segment BEFORE the
 * match has to be a single-line error name.
 */
const baseConverted = (e: ResilientError): boolean => {
  if (e.type === '') return false
  const at = e.message.indexOf(`: ${e.type}`)
  if (at < 0) return false
  const rest = e.message.slice(at + e.type.length + 2)

  return !e.message.slice(0, at).includes('\n') && (rest === '' || rest.startsWith('\n'))
}

/**
 * Where the marker actually is, for anything that can carry one.
 *
 * `ResilientError.ensure` rebuilds a class this process never registered by putting the whole
 * marshalled string in `type` and its own local STACK in `message` — and every refusal the
 * platform raises is such a class, since they are declared in packages the SDK does not depend on.
 * So the marker can be in either field, and a stored `job.error` carries it as a bare string.
 *
 * {@link baseConverted} is asked FIRST, because that rebuild is the one shape where the stack sits
 * outside the marshalling and the fields are swapped: everything below reads `message` as text and
 * would hand the trace straight to the reader.
 */
const textOf = (e: unknown): string => {
  if (typeof e === 'string') return e
  if (!(e instanceof Error)) return String(e ?? '')
  if (e instanceof ResilientError && baseConverted(e)) return e.type
  const type = e instanceof ResilientError ? e.type : ''
  if (e.message.includes(ResilientError.separator)) return e.message
  if (type.includes(ResilientError.separator)) return type

  return e.message !== '' ? e.message : type
}

/**
 * What a refusal SAYS, with the marshalling and the stack taken off it.
 *
 * A marshalled error is `type|||message|||stack`, so the middle segment is the marker and the last
 * one is a stack trace from a machine the reader has no access to. What is left is the marker
 * alone — which is the fallback whenever nothing in {@link REFUSALS} recognises it, because a
 * marker names the refusal even when no sentence has been written for it yet.
 *
 * Text that was never marshalled is returned exactly as it is. A stack only ever arrives inside
 * the marshalling, and the same field carries things that are not refusals at all — a job's
 * `error` doubles as the build warning a slot recorded, and cutting that at the first line that
 * looks like a stack frame would throw away the diagnostics somebody asked for.
 */
export const refusalMessage = (e: unknown): string => {
  const parts = textOf(e).split(ResilientError.separator)

  return parts.length > 1 ? withoutStack(parts[1] ?? '') : (parts[0] ?? '')
}

/** Said where the platform refused and said nothing about why at all. */
export const UNKNOWN_REFUSAL = 'The platform refused this and said nothing about why. Read'
  + ' project_status, or conversion_status for a conversion, before retrying.'

/** Said after a marker no sentence has been written for: the marker names it, this says what next. */
export const UNPHRASED_REFUSAL = 'That is the marker the platform refused with, and nothing here'
  + ' has a sentence for it yet. Read conversion_status for a conversion, project_status'
  + ' otherwise, before deciding whether anything is worth retrying.'

/**
 * Wire text a refusal travels as — `package:family:reason`, with any detail after it.
 *
 * What separates an unphrased MARKER from the other things this same field carries: a deadline
 * message, a build warning, a gateway error. Only a marker earns the next-step half, because only
 * a marker is a refusal the parent can neither read nor act on; a build warning is diagnostics
 * somebody asked for and is returned exactly as it stands.
 */
const MARKER_SHAPE = /^[a-z][\w-]*(?::[\w.-]+)+/

/**
 * The one sentence a parent agent is given for anything that refused it.
 *
 * The reader is a language model holding a tool result, and it acts on what it reads: a marshalled
 * type name followed by a stack trace tells it only that something went wrong somewhere, so it
 * retries a call that can never succeed, or reports the server as broken. A refusal is an ANSWER —
 * this origin is the project, that decision is not available here, the balance will not cover it —
 * and every one of them has something the parent should do next.
 *
 * An unknown marker keeps that property rather than dropping it: the marker stays, because it is
 * the honest answer as the platform grows refusals faster than phrasings, and {@link
 * UNPHRASED_REFUSAL} names the tool to call — a parent left holding wire text alone has neither.
 */
export const refusalPhrase = (e: unknown): string => {
  const message = refusalMessage(e)
  if (message === '') return UNKNOWN_REFUSAL

  const known = REFUSALS.find(entry => message.includes(entry.marker))
  if (known == null) {
    return MARKER_SHAPE.test(message) ? `${message}\n${UNPHRASED_REFUSAL}` : message
  }

  const detail = message.slice(message.indexOf(known.marker) + known.marker.length)
    .replace(/^:/, '').trim()

  return known.phrase(detail)
}
