import { SubProject } from '../slot/consts.js'
import { ViableSkill } from '../skills/consts.js'
import { ViablePersona } from '../skills/roles.js'
import { aiLibraryList, gameLibraryList } from '../skills/catalogue.js'
import type { BlueprintPatch } from './types.js'

/**
 * WHICH KIND of product is being built on a blueprint.
 *
 * A blueprint says what the STACK is — the language, the framework, the topology, the seeds. A
 * case says what is being built ON it, and that is a different question with different consumers:
 * the analyst framing the brief, the architect deciding whether a story needs a queue, the coder
 * choosing which packages it may import.
 *
 * Deliberately NOT a second blueprint. Everything a case has to say is already a blueprint field,
 * so a case is a PATCH and the resolution order stays base → case → per-run overrides. That is
 * also why adding one is a data change: nothing reads `BlueprintCase` except the table below and
 * the prompt that classifies a project into it.
 */
export enum BlueprintCase {
  /** A web application whose every feature fits inside a request. No queue, no worker, no agents. */
  Web = 'web',
  /** A web application with work that genuinely belongs off the request path. */
  Scalable = 'scalable',
  /** The product's value comes from ordered, deterministic model-driven steps. */
  AiPipeline = 'ai-pipeline',
  /** The product's value comes from an agent that decides its own path through tools. */
  AiAgent = 'ai-agent',
  /** A browser game: a three.js scene with an ordinary React interface over it. */
  Game = 'game',
}

/**
 * How a game is played, which decides who owns its state.
 *
 * Recorded beside the case rather than folded into it, because it changes nothing about the
 * dependencies and everything about where the logic goes. `OnlineTurn` is the default for
 * anything multiplayer unless the brief plainly asks for live play — it is the shape that
 * actually builds, and it needs no socket, no tick loop and no reconciliation.
 */
export enum GameKind {
  Casual = 'casual',
  OnlineTurn = 'online-turn',
  OnlineLive = 'online-live',
}

export interface BlueprintCaseDefinition {
  id: BlueprintCase
  title: string
  /**
   * What this case is FOR, as the classifier prompt reads it.
   *
   * A pure constant, like every skill body: it lands in a cached prompt region, and one
   * interpolated byte invalidates the prefix for every project classified after it.
   */
  when: string
  /** Applied between the base blueprint and the run's own overrides. A case is nothing else. */
  patch: BlueprintPatch
}

/** What every AI case installs. The langchain peers are declared here, at ONE range. */
const AI_DEPS = {
  [SubProject.Backend]: {
    '@owlmeans/llm': '^0.1.18-rc.13',
    '@owlmeans/agent': '^0.1.18-rc.16',
    '@langchain/core': '^1.2.9',
    '@langchain/anthropic': '^1.5.8',
    '@langchain/openai': '^1.5.10',
    '@langchain/langgraph': '^1.4.13',
    '@langchain/langgraph-checkpoint': '^1.1.5',
  },
}

/** The library allow-list a backend persona gets once the AI packages are installed. */
const AI_LIBRARIES = {
  [SubProject.Backend]: aiLibraryList,
  [SubProject.Api]: aiLibraryList,
  [SubProject.Worker]: aiLibraryList,
}

/** Skills every AI case adds on top of the blueprint's own. */
const AI_SKILLS = [
  ViableSkill.AgenticChoice,
  ViableSkill.TargetLlm,
  ViableSkill.LibrariesAi,
]

/**
 * What the analysis stage is told about a product whose value is a model.
 *
 * The pairing rule is the load-bearing one: an agent holds no permissions and owns no screen, so
 * a story that is the AGENT's work is invisible unless a human story starts it and watches it.
 */
/**
 * What the API side is told once a project may have a queue.
 *
 * The endpoint that starts slow work is the PRODUCER, and it is generated by a persona that
 * otherwise has no reason to know a broker exists. Its job alias is declared before it runs
 * (`runtime-declare`), so by the time this coder writes the handler there is something to enqueue
 * onto — and this is what tells it to, instead of doing the work inline behind a request the user
 * is waiting on.
 */
const PRODUCER_PERSONA_SKILLS = {
  [ViablePersona.ApiArchitect]: [ViableSkill.QueueDiscipline, ViableSkill.WorkerJobs],
  [ViablePersona.ApiCoder]: [ViableSkill.WorkerJobs],
}

const AI_PERSONA_SKILLS = {
  ...PRODUCER_PERSONA_SKILLS,
  [ViablePersona.BusinessAnalyst]: [ViableSkill.AgenticChoice],
  [ViablePersona.UxDesigner]: [ViableSkill.AgenticChoice],
  [ViablePersona.RuntimeArchitect]: [ViableSkill.AgenticChoice, ViableSkill.TargetLlm],
  [ViablePersona.WorkerCoder]: [
    ViableSkill.AgenticChoice, ViableSkill.TargetLlm, ViableSkill.LibrariesAi,
  ],
}

const GAME_PERSONA_SKILLS = {
  [ViablePersona.BusinessAnalyst]: [ViableSkill.GameDesign],
  [ViablePersona.UxDesigner]: [ViableSkill.GameDesign, ViableSkill.GameUi],
  [ViablePersona.VisualDesigner]: [ViableSkill.GameUi],
  [ViablePersona.ComponentArchitect]: [ViableSkill.GameScene, ViableSkill.GameUi],
  [ViablePersona.LayoutArchitect]: [ViableSkill.GameScene, ViableSkill.GameUi],
  [ViablePersona.UiViewCoder]: [
    ViableSkill.GameScene, ViableSkill.GameUi, ViableSkill.LibrariesGame,
  ],
  [ViablePersona.RuntimeArchitect]: [ViableSkill.GameNetworking],
  [ViablePersona.WorkerCoder]: [ViableSkill.GameNetworking],
  [ViablePersona.ApiArchitect]: [ViableSkill.GameNetworking],
  [ViablePersona.ApiCoder]: [ViableSkill.GameNetworking],
}

/**
 * The cases the platform ships.
 *
 * Read as a table: the left column is what a prompt has to look like, the right column is what
 * that costs the generated application. Nothing here turns a capability on without also
 * installing what makes it real — a blueprint that promises `agents` over a manifest with no
 * `@owlmeans/agent` in it produces a story that reports success and a library that will not
 * compile.
 */
export const BLUEPRINT_CASES: Record<BlueprintCase, BlueprintCaseDefinition> = {
  [BlueprintCase.Web]: {
    id: BlueprintCase.Web,
    title: 'Web application',
    when: `
Everything the product does fits inside a request: forms, lists, records, search, reports a
person waits a second for. Nothing has to survive the tab closing, nothing calls a slow third
party, nothing walks an unbounded set, nothing is scheduled. Most products are this.
`.trim(),
    patch: {
      packages: {
        capabilities: { postgres: true, kv: false, queue: false, worker: false, agents: false, validation: true },
      },
    },
  },

  [BlueprintCase.Scalable]: {
    id: BlueprintCase.Scalable,
    title: 'Web application with background work',
    when: `
Like a web application, except that some named part of it genuinely cannot run inside a request:
it walks every row a user owns, talks to a slow or rate-limited third party, is scheduled or
repeated, must survive the tab closing, or must be retried without the user doing anything.
Choose this only when you can NAME that part; "it might get slow" is not it.

NOT this when the slow part is a MODEL. Background work whose content comes out of a language
model is one of the two AI kinds below, and choosing this one for it leaves the application unable
to call a model at all.
`.trim(),
    patch: {
      packages: {
        capabilities: { postgres: true, kv: true, queue: true, worker: true, agents: false, validation: true },
        personaSkills: PRODUCER_PERSONA_SKILLS,
      },
    },
  },

  [BlueprintCase.AiPipeline]: {
    id: BlueprintCase.AiPipeline,
    title: 'AI pipeline',
    when: `
The product's value comes from a language model, and the work it does is a KNOWN sequence:
transcribe then summarise then file; extract then validate then store; draft then check then send.
You can name the steps before it runs. The application decides the order; the model performs each
step.

Any product whose OUTPUT is written by a model is this kind or the one below — never a plain web
application, and never merely a scalable one.
`.trim(),
    patch: {
      packages: {
        capabilities: { postgres: true, kv: true, queue: true, worker: true, agents: true, validation: true },
        deps: AI_DEPS,
        libraries: AI_LIBRARIES,
        skills: AI_SKILLS,
        personaSkills: AI_PERSONA_SKILLS,
      },
    },
  },

  [BlueprintCase.AiAgent]: {
    id: BlueprintCase.AiAgent,
    title: 'AI agent',
    when: `
The product's value comes from a model that decides its own path: how many steps the work takes
cannot be predicted, and which tool to reach for next is a judgement rather than a rule anyone
could write down. Choose this over an AI pipeline only when the order genuinely cannot be fixed
in advance.
`.trim(),
    patch: {
      packages: {
        capabilities: { postgres: true, kv: true, queue: true, worker: true, agents: true, validation: true },
        deps: {
          [SubProject.Backend]: {
            ...AI_DEPS[SubProject.Backend],
            '@owlmeans/agent-skills': '^0.1.18-rc.12',
          },
        },
        libraries: AI_LIBRARIES,
        skills: [...AI_SKILLS, ViableSkill.TargetAgentTools],
        personaSkills: {
          ...AI_PERSONA_SKILLS,
          [ViablePersona.WorkerCoder]: [
            ...AI_PERSONA_SKILLS[ViablePersona.WorkerCoder], ViableSkill.TargetAgentTools,
          ],
        },
      },
    },
  },

  [BlueprintCase.Game]: {
    id: BlueprintCase.Game,
    title: 'Browser game',
    when: `
The person asked for a GAME, in those words or unmistakably — something played rather than used,
with a loop, a score or a win condition. Never infer this from "gamified", "playful", "fun" or a
leaderboard attached to an ordinary product. If the prompt does not plainly ask for a game, this
is not it.
`.trim(),
    patch: {
      packages: {
        capabilities: { postgres: true, kv: true, queue: true, worker: true, agents: false, validation: true },
        deps: {
          [SubProject.Web]: { three: '^0.186.0', '@types/three': '^0.185.4' },
        },
        libraries: { [SubProject.Web]: gameLibraryList, 'ui-state': gameLibraryList },
        skills: [ViableSkill.GameScene, ViableSkill.GameUi, ViableSkill.LibrariesGame],
        personaSkills: { ...PRODUCER_PERSONA_SKILLS, ...GAME_PERSONA_SKILLS },
      },
    },
  },
}

/**
 * The case a reference names, or `undefined`.
 *
 * Total over anything: an unknown name, a name from a deploy this one does not have, and an
 * absent one all read the same way — no patch, which is the base blueprint. That is the only
 * answer that cannot take a capability away from a project that already has it.
 */
export const blueprintCaseOf = (name?: string): BlueprintCaseDefinition | undefined =>
  name == null ? undefined : (BLUEPRINT_CASES as Record<string, BlueprintCaseDefinition>)[name]

/** Every case the platform ships, in the order a classifier should weigh them. */
export const BLUEPRINT_CASE_ORDER: BlueprintCase[] = [
  BlueprintCase.Web,
  BlueprintCase.Scalable,
  BlueprintCase.AiPipeline,
  BlueprintCase.AiAgent,
  BlueprintCase.Game,
]
